# modelled on https://github.com/sta210-s22/website
#https://atheobold.github.io/stat-313-website/ stolen from also
project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "MPS 140"
  site-url: "https://njaalf.github.io/MPS-140/"
  
  sidebar:
      background: "#D9E3E4"
      logo: "images/icon.png"
      pinned: true
      align: center
      style: "docked"
      search: true
      collapse-level: 1
      contents:
        - section: "Kursinfo"
          contents: 
            - href: emnebeskrivelse.qmd
              text: Emnebeskrivelse
        - section: "Samlinger"
          contents:
            - href: samlinger/samling1.qmd
              text: "Samling 1"
        - section: "R"
          contents:
            - href: Ressurser.qmd
              text: Installasjon
        - section: "Data"
          contents: 
            - href: data/smartphone_wellbeing.rds
              text: "Goldilocks hele datasett"
            - href: data/goldilocksutvalg.rds
              text: "Goldilocks utvalg av 400 ungdommer"
        - section: "Eksamen"
          contents:
            - href: omeksamen.qmd
              text: Om eksamen
              
format:
      html:
        theme:
          light: [cosmo, theme.scss]
          dark: [cosmo, theme-dark.scss]
        mainfont: "Atkinson Hyperlegible"
        code-copy: true
        code-overflow: wrap
        toc: false

