---
title: "MPS 140: Kvantitativ forskningsmetode og statistikk"
tbl-colwidths: [10,30,10,10,10]
---

# FYSISKE SAMLINGER

<!-- [📖](samlinger/samling1.qmd "Samling 1")  -->

<!-- [📖](samlinger/samling2.qmd "Samling 2") -->

::: column-screen-inset-right
| Dato           | Tema                              |              Forberedelser               |                               Presentasjoner                                | R                       |                Oppgaver                 |
|------------|------------|:----------:|:----------:|------------|:----------:|
| 23.01: 1215-16 | Intro og grunnleggende statistikk | [📖](samlinger/samling1.qmd "Samling 1") | [🖥](slides/slides1.qmd "Foiler 1") [🖥](slides/stat_review.pdf "Repetisjon") | [📋](R/R1.qmd "R kode") | [📋](quiz/samling1_mps140.pdf "Oppg 1") |
| 05.03: 815-16  | Psykometri                        | [📖](samlinger/samling3.qmd "Samling 3") |  [🖥](slides/slides3a.qmd "Foiler 3A") [🖥](slides/slides3b.qmd "Foiler 3b")  |                         |  [📋](quiz/quiz%205mars.qmd "Oppg 1")   |
| 09.04: 815-16  | Latente variable                  | [📖](samlinger/samling5.qmd "Samling 5") |                                                                             |                         |                                         |
| 03.06          | Eksamen                           |                                          |                                                                             |                         |                                         |
:::

# DIGITALE SAMLINGER

::: column-screen-inset-right
| Dato        | Tema                                                         |              Forberedelser               |            Presentasjon            | R                          |                  Oppgaver                   |
|------------|------------|:----------:|:----------:|------------|:----------:|
| 06.02: 9-12 | R og regresjonsmodellen                                      | [📖](samlinger/samling2.qmd "Samling 1") | [🖥](slides/slides2.qmd "Foiler 2") | [📋](R/digR1.qmd "R kode") | [📋](quiz/digsamling1_mps140.pdf "Oppg 2")  |
| 19.03: 9-12 | Forskningsmetoder i psykologi + Forutsetninger for regresjon | [📖](samlinger/samling4.qmd "Samling 4") | [🖥](slides/slides4.qmd "Foiler 4") |                            | [📋](quiz/quiz19mars_medfasit.qmd "Oppg 4") |
| 23.04:9-12  | Latente variable                                             |                                          |                                    |                            |                                             |
| 07.05: 9-12 | Eksamensforberedelse                                         |                                          |                                    |                            |                                             |
:::
