---
title: "Fysisk samling - 4 mars"
subtitle: "Multippel regresjon og M친ling av psykologiske konstrukter "
editor: visual
---

L칝ringsm친l:

-   칀 bli enda mere kjent med multippel regresjon

-   칀 forst친 hvordan psykologer fors칮ker 친 m친le psykologiske konstrukt, slik som stress, angst og motivasjon

-   Validitet og reliabilitet til psykologiske m친linger

## Forberedelser

-   游닀 Repeter stoffet i kapittel 22 om enkel regresjon i Statistikk og Dataanalyse. Vi skal ogs친 repetere p-verdi og konfidensintervall.

-   Sjekk ut videoer om reliabilitet og validitet p친 youtube. For eksempel er det en serie med tre videoer her: [Reliabilitet og validitet](https://www.youtube.com/watch?v=DS8Hw0Ort4w)

-   Les om hvordan vi m친ler jobb-stress i artikkelen [Sevic Foldnes og Br칮nnick 2024](https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2024.1297194/full "Measuring digital stress in Norway")

-   Last ned pakkene *psych* i R som kan regne ut reliabilitet, for eksempel Cronbach's $\alpha$. N친r du laster psych pakken inn i R sesjonen s친 f친r du tilgang til et datasett bfi som har 25 personlighet items. De fem f칮rste er "Agreeableness", osv.

La oss pr칮ve dette p친 bfi datasettet (becks depression inventory)

```{r}
# last ned et datasett med Eysenck personality og Big Five 
     #kikke p친 de f칮rste radene
library(psych)#loade psych pakken

#definere constructene i bfi datasettet
#legg merke til at feks A1 item "Am indifferent to the feelings of others"
# har feil retning og m친 snus med et minustegn:
keys.list <- list(agree=c("-A1","A2","A3","A4","A5"),
                  conscientious=c("C1","C2","C2","-C4","-C5"),
                  extraversion=c("-E1","-E2","E3","E4","E5"),
                  neuroticism=c("N1","N2","N3","N4","N5"),
                  openness = c("O1","-O2","O3","O4","-O5"))
#print ut flere forskjellige m친l for reliabilitet, blant annet alpha
#reliability(keys=keys.list, items=bfi)
```
